### ISSUE TITLE
Content Updates 

### ISSUE THREAD

**Issue by gbinal** [18F/pulse#100]
Some content edits:

- [X] Explain why the number of domains are different for HTTPS and DAP.
- [X] Clarify how the `/analytics` section handles inactive and redirecting domains.
- [X] The column header on `/analytics` should probably be Participates in Digital Analytics Program not Participates in Analytics.
- [ ] How does Pulse measure HTTPS? (#125)
- [ ] How does Pulse measure participation in the Digital Analytics Program? (#125)
- [ ] How often does the information on Pulse update?
- [ ] Where can I share an idea for something else you should track?

**Comment by gbinal** [comment]
There should be a new FAQ question explaining why the number of domains are different for `HTTPS` and `DAP`.

**Comment by gbinal** [comment]
On a similar but different note, we need to clarify how the /DAP section handles inactive and redirecting domains.

**Comment by gbinal** [comment]
The column header on /dap should probably be `Participates in Digital Analytics Program` not `Participates in Analytics`.

**Comment by gbinal** [comment]
Add 2 questions to /about:  
* How does Pulse measure HTTPS?  
* How does Pulse measure participation in the Digital Analytics Program?

**Comment by gbinal** [comment]
Add a question to /about: 
* How often does the information on Pulse update?

**Comment by gbinal** [comment]
Add a question to /about: 
* Where can I share an idea for something else you should track?

**Comment by konklone** [comment]
@gbinal, I collapsed your various todos into a checkbox list at the top of the issue, and marked which ones I think are done, and put issue/PR #'s next to ones awaiting merge. I suggest adding any more todos as checkboxes above.

**Comment by gbinal** [comment]
Looks like this is good.  Closing.
