### ISSUE TITLE
consider an email option for contact us

### ISSUE THREAD

**Issue by gbinal** [18F/pulse#103]
Yes, we should drive folks to use this issue tracker, but some will want to email instead.  Should we setup `pulse@gsa.gov` and add it to the /about page as another means of getting in touch?  @jtexnl, I defer to you.

**Comment by konklone** [comment]
Note, we can do `pulse@cio.gov` as well, just as easily.

**Comment by konklone** [comment]
@jtexnl, want to ring in here? If we're going to put in a ticket to create this, it should be soon.

**Comment by jtexnl** [comment]
Finally got feedback from the team. Looks like pulse@cio.gov is the way everyone wants to go.

**Comment by konklone** [comment]
@gbinal Since you've done this before, are you up for filing the ticket?

**Comment by gbinal** [comment]
FYI, this is set up.  

I've added it to the bottom of /about with https://github.com/18F/pulse/pull/154.
