### ISSUE TITLE
Data update process should be clear and documented

### ISSUE THREAD

**Issue by konklone** [18F/pulse#105]
There should be a clear, straightforward process and set of commands to update the dataset used by the tool.

This ticket can be resolved by creating a `data.md` or `update.md` that follows the process of:

* Downloading the latest snapshot of data on participating domains from the Digital Analytics Program.
* Downloading the latest set of federal .gov domains.
* Having the correct tools and dependencies installed (`domain-scan` and its dependencies, any others).
* Setting up and running `domain-scan` using the latest .gov domains, and the latest DAP participation data.
* Taking the resulting JSON and CSVs from `domain-scan`, and running the data scripts in this repository on them to create the datasets that Pulse needs to render information.
* Publishing these datasets to the project, either by committing to GitHub and triggering an auto-deploy, or by publishing to S3.

**Comment by gbinal** [comment]
@konklone - Let's go with what we have in hand right now, for now.  Whether CSVs or JSON and even if numbers as opposed to the processed information on the site, it'll be better to add what we have to /about now and iterate as we go.

**Comment by gbinal** [comment]
Sorry - wrong issue.  Please ignore the above.

**Comment by gbinal** [comment]
To this, though - @konklone, do you have an ETA for when you can document a first pass at this?
