### ISSUE TITLE
Agency tabs and data grouping

### ISSUE THREAD

**Issue by konklone** [18F/pulse#106]
A "by agency" tab on the HTTPS and DAP landing pages that groups data by agency, rather than by domain.

This involves both front-end buildout work, and data pipelining work to create data grouped appropriately for this view.

**Comment by juliaelman** [comment]
Both #77 and #78 are effected by this. Just noting here so that we can keep those in-sync with this issue.

**Comment by konklone** [comment]
Closed by #110.
