### ISSUE TITLE
Release blog post

### ISSUE THREAD

**Issue by konklone** [18F/pulse#108]
A blog post on the 18F blog about Pulse (or whatever our final name may be), once we and OGP think it's ready for the attention. This could be cross-posted with OGP, or we could both post about it separately and 18F could take the more tech-heavy approach (as we did with the DAP).

**Comment by gbinal** [comment]
Memorializing a conversation today, it looks like it might be best to do separately posts that can go through the process asynchronously.  There's no need for a 'coordinated comms rollout' for this.  

We can discuss in the sprint 3 wrapup but we think it's best to get the first posts out the door as soon after sprint 3 as possible, while conveying that the project is very much still a living project and welcome engagement.

**Comment by gbinal** [comment]
Great work!  https://18f.gsa.gov/2015/06/02/taking-the-pulse-of-the-federal-governments-web-presence/
