### ISSUE TITLE
Call out 'How to Do Better!' information 

### ISSUE THREAD

**Issue by gbinal** [18F/pulse#113]
I think we should strongly call out in the headers of /https and /analytics the paths by which agencies can do better.  Perhaps:  

"Need help adopting HTTPS?  Go here!" [link to section of https.cio.gov that specifically offers help, needs creating I think.]

"Need help joining DAP?  Go here!" [link to http://www.digitalgov.gov/services/dap/]

**Comment by juliaelman** [comment]
Just making note, this is one of the tasks outlined here: https://github.com/18F/dotgov-dashboard/issues/76#issue-73821162

**Comment by konklone** [comment]
:+1: to all of this. Closing in favor of continuing to track in #76.

**Comment by konklone** [comment]
Er, wait, we also said we'd split this out into a separate nav item and landing page. Which I think is smart. So let's track this here.

**Comment by juliaelman** [comment]
Resolved by #125. There will most likely be some refining, but this generally covers the purpose of this issue.
