### ISSUE TITLE
promote 'Feedback' link more?  

### ISSUE THREAD

**Issue by gbinal** [18F/pulse#115]
Given how strongly the intended audience will likely feel about iterating and improving this site, I wonder if we shouldn't promote a `Feedback` path that links to this issue tracker more.  Offhand, I don't it would be inappropriate in the nav bar but am open to other ideas.

**Comment by juliaelman** [comment]
I agree. Would Github issues suffice?

**Comment by konklone** [comment]
Let's start with it and see if it needs to go further from there.

The About copy that @jtexnl started includes a feedback email, and I've suggested at least adding a link to GitHub Issues. For a top-level nav item, I'd prefer GitHub to email.

**Comment by juliaelman** [comment]
One solution would be to add a "Feedback" link to the top nav and then link it to Github issues.
