### ISSUE TITLE
Ability to expand websites under a given agency?

### ISSUE THREAD

**Issue by alex** [18F/pulse#118]
It seems like it'd be useful to be able to expand websites under an agency, so you can see which sites have the features, and which do not.

**Comment by juliaelman** [comment]
Thanks for the suggestion! Maybe we could think about a Phase One step and add an "Agency" column to the "By Domains" tab?

**Comment by konklone** [comment]
I wonder if we can support permalinks to specifically filtered lists, like @gbinal said. If so, we could link from the agency list's "No. of Domains" amounts to the domain list filtered to that agency.

**Comment by gbinal** [comment]
Yeah - I didn't appreciate it enough until now but def. realize that a major use case for both the by domain and by agency tabs will be "I want to see my agency's domains".  

I think something that gets us by will be pretty important with this.  Thinking about more.

**Comment by konklone** [comment]
Moving to Sprint 3, and hopefully this is a simple addition after #101 is resolved.

**Comment by gbinal** [comment]
Thinking about this just now and two 'easy' solutions' seem to me to be:  
* Add a column next to `by agency` (one way to possibly keep it narrow and tidy would be to use [the social media registry api](http://registry.usa.gov/agencies.json) to provide acronyms and have tooltips show the full agency name).  
* Just add the agency acronym in brackets after the domain, e.g. `18f.gov [GSA]`.  That way folks can use the quickfilter to find their agency.  

The 2nd idea isn't perfection but it might be easiest and would do to get us off the ground.

**Comment by gbinal** [comment]
P.S. The api endpoint I linked in the comment above has some ability to set query parameters.  For more, check out the `/agencies` references on [this page](http://www.usa.gov/About/developer-resources/social-media-registry.shtml).

**Comment by konklone** [comment]
Bear in mind we're using agency names that come straight out of the .gov registry data, some combination of GSA and Verisign data. So like, USPS and USPS OIG are listed separately. It's not standard, and I'm sure we'll get questions, but we also can't cleanly and automatically map our data onto standard acronyms as a result.

**Comment by konklone** [comment]
I think starting from the Agencies tab and linking the number of domains, e.g. "16 domains", and having that bring the user to a filtered Domains tab to that agency, would probably be a simple place to start, but continue to be open to other ideas. =)

**Comment by gbinal** [comment]
> I think starting from the Agencies tab and linking the number of domains, e.g. "16 domains", and having that bring the user to a filtered Domains tab to that agency, would probably be a simple place to start, but continue to be open to other ideas.

That'd work great in my book.

**Comment by juliaelman** [comment]
Closed with PR #156
