### ISSUE TITLE
"Sort" indicators on "By Agency" table are confusingly placed

### ISSUE THREAD

**Issue by alex** [18F/pulse#121]
(Well, I guess I don't know if they're objectively confusing, but I was confused by them)

Specifically, the up/down arrows are right next to text, but they are _not_ assosciated with that columns. So the arrows next to "HTTPS Enabled?" are actually owned by "No. of domains"

**Comment by juliaelman** [comment]
Thanks for the feedback @alex! We're aware of this issue and have outlined a solve here:  https://github.com/18F/pulse/issues/98

Closing this issue as a duplicate.

**Comment by alex** [comment]
Doh, sorry I missed that.
