### ISSUE TITLE
"Completion bar" rendering oddly

### ISSUE THREAD

**Issue by alex** [18F/pulse#131]
This is latest Chrome on OS X Yosemite, viewing the analytics by agency page.
![screen shot 2015-05-25 at 10 57 32 pm](https://cloud.githubusercontent.com/assets/772/7804474/8c8fba72-0331-11e5-957c-9fd6bb163adf.png)

**Comment by alex** [comment]
It looks like anything below 17% exhibits the behavior, with smaller percentages being more obvious.

**Comment by jtexnl** [comment]
I got the same comment from someone during user testing last night; it's especially an issue on the https bars, where there are quite a few 2% and 3% scores. The darkened color goes to the left of the bar. Would we have to move away from the rounded bar to address this, or is there another way?

**Comment by juliaelman** [comment]
On it.

**Comment by jtexnl** [comment]
It looks a lot better, but 1-3% are still rendering oddly for me

**Comment by jtexnl** [comment]
![image](https://cloud.githubusercontent.com/assets/6758591/7842246/0cf77710-0470-11e5-89e8-295d1c1ed826.png)
