### ISSUE TITLE
address language in analytics donut 

### ISSUE THREAD

**Issue by gbinal** [18F/pulse#132]
A couple folks in the user testing right now arrive at the site, love the site, and immediately believe that the donut graph on the right represents the *percent of .gov websites that have website analytics at all*.  

To folks seeing this the first time, I absolutely think that will be what's conveyed, a misunderstanding that will be problematic out of the box.  What do folks think about phrasing that could alleviate this?  

* We could say 'Participates in DAP' and strongly call out 'DAP' as a hyperlink that opens in a new tab to the explanation page.  
* We could say 'Participates in the Digital Analytics Program' or 'Participates in GSA Analytics`.  
* Other ideas.

**Comment by juliaelman** [comment]
@gbinal "Participates in Website Analytics"

**Comment by konklone** [comment]
> "Participates in Website Analytics"

I don't think that will resolve the core issue of people being not distinguishing between web analytics in general, and the DAP in particular.

I think of all of these, I prefer "Participates in the Digital Analytics Program", long as it is. :/

cc @smarina04 @tdlowden

**Comment by konklone** [comment]
Relatedly, I just saw this in user feedback:

> How might a non-tech savvy person find out what HTTPS is and why it is important immediately? Suggest using the word "secure" in some way, or incorporating that into the front-page explanation. Maybe a tooltip?

Maybe we should expand "Analytics" to "Digital Analytics Program", and "HTTPS" to "Secure HTTP". This is what we already ended up doing for the headers on their respective pages.

**Comment by gbinal** [comment]
Not to belabor it but it occurs to me that this might be worth at lease a temporary fix before the meeting tomorrow.  In it's current state, I think a good chunk of CIOs will be confused and defensive right out of the bat.  If we can't find an elegant way to fit in more text, I'd rather it say '34% use DAP' than '34% use analytics' when we show it to them.  :/

**Comment by tdlowden** [comment]
+1 to @gbinal and @konklone. We definitely need to make a clear distinction between DAP vs. analytics tools in general. I am also for the link to DAP explanation in tandem with language change in the donut.

**Comment by gbinal** [comment]
Thanks - that change makes a big difference.
