### ISSUE TITLE
hyperlink domains column in 'by domains' tabs.  

### ISSUE THREAD

**Issue by gbinal** [18F/pulse#134]
Multiple users in tonight's feedback session indicated that, when on a `By Domains` tab, they were often interested by a domain they saw and would want to go to the site to further see what it was about.  In other words, they wanted to click on the domains.   After trying that, they would fall back on copying and pasting the domain and opening a new tab.   

The individual domains should be hyperlinked and set to open in a new tab.

**Comment by konklone** [comment]
Great idea. Doe in https://github.com/18F/pulse/pull/137.
