### ISSUE TITLE
verbs in donut charts should be plural not singular.  

### ISSUE THREAD

**Issue by gbinal** [18F/pulse#135]
34% [of .gov websites] uses HTTPS -> 34% [of .gov websites] use HTTPS
33% [of .gov websites] participates in ....   ->  33% [of .gov websites] participate in ....

**Comment by konklone** [comment]
I saw @juliaelman make a deliberate change to go in the opposite direction -- deferring to her for a response here.

**Comment by juliaelman** [comment]
Agreeing with this verbiage change makes more sense! :+1:

**Comment by konklone** [comment]
@gbinal Care to do a PR?

**Comment by gbinal** [comment]
Okay - here you go - https://github.com/18F/pulse/pull/139

**Comment by juliaelman** [comment]
Fixed! Thanks @gbinal :D
