### ISSUE TITLE
weigh changing the feedback link 

### ISSUE THREAD

**Issue by gbinal** [18F/pulse#136]
From the ['create a new issue' page](https://github.com/18F/pulse/issues/new) to the [issue tracker](https://github.com/18F/pulse/issues) itself.  

For many users, I think this will give more context to where they are and what the type of feedback that has already been given.  

This is all the more so when you realize that anyone who doesn't have a github account or isn't logged in just goes a login screen.  (Try the link in an incognito window to easily see what I mean).  

![screen shot 2015-05-26 at 9 26 47 pm](https://cloud.githubusercontent.com/assets/633088/7826862/f9ad6660-03ed-11e5-9f34-1463989350e3.png)

**Comment by konklone** [comment]
:+1: @gbinal Send a PR?

**Comment by gbinal** [comment]
Roger - https://github.com/18F/pulse/pull/138

**Comment by konklone** [comment]
Done in #138.
