### ISSUE TITLE
Freeze Title Row in Data Table

### ISSUE THREAD

**Issue by jtexnl** [18F/pulse#145]
This was brought up in user testing last night: if a user wants to view lots of rows (and we allow 100), they have no way of knowing where in the table they are once they scroll down in the data and the top row is no longer visible. Would it be possible to freeze the top row of the data so that the column headers are visible to a user scrolling through the table?

**Comment by juliaelman** [comment]
@jtexnl yup! Looks like we can do that with this: https://www.datatables.net/extensions/fixedheader/ Going to hold off from adding to Sprint 3 until after today's findings. Thanks for posting this!

**Comment by gbinal** [comment]
It's a good idea but I'm not sure that we're going to get to it.  I'm going to go ahead and close.
