### ISSUE TITLE
/https/domains/ plus sign and link to agency website need spacing

### ISSUE THREAD

**Issue by juliaelman** [18F/pulse#151]
Currently, there is little space between the plus sign and the link to the agency website on `/https/domains/`. This was noted in this pull request:  https://github.com/18F/pulse/pull/149#issuecomment-106014599 and see screenshot below for reference too:

![screen shot 2015-05-27 at 2 07 07 pm](https://cloud.githubusercontent.com/assets/955558/7843727/7f422b4a-0479-11e5-9945-db601a90d060.png)

**Comment by juliaelman** [comment]
This issue may resolve itself once we start building out the individual pages for each domain too.

**Comment by juliaelman** [comment]
With the addition of the hover state to the rows, this seems to be a non-issue. See #174 for fix.

**Comment by konklone** [comment]
Totally right, good catch.
