### ISSUE TITLE
GA version, UA Code, and anonymizeIp settings

### ISSUE THREAD

**Issue by geramirez** [18F/pulse#152]
I was working on an audit of 18F's sites GA settings and found a way to [extract GA info using javascript and a headless browser](https://github.com/ramirezg/GAAuditor/blob/master/GAChecker.py).  

For now I'm using a headless browser to run the javascript snippet below and then parse the logs. I figured the concept might be helpful for this project too. 

```javascript
if (typeof ga === "function") {
    console.log('ga_version: Google Analytics Universal');
    console.log('ga_ua_code: ' + ga.getAll()[0].get('trackingId'));
    console.log('ga_ua_anon: ' + ga.getAll()[0].get('anonymizeIp'));
}
else if (typeof _sendPageview === "function") {
    console.log('ga_version: Google Analytics Legacy');
    console.log('ga_ua_code: ' + oCONFIG.GWT_UAID[0]);
    console.log('ga_ua_anon: ' + oCONFIG.ANONYMIZE_IP);
}
else {
    console.log('ga_version: No Google Analytics');
    console.log('ga_ua_code: No UA Code');
    console.log('ga_ua_anon: No UA Code');
}
```

**Comment by gbinal** [comment]
It doesn't look like we're going to expand the GA scanning detail on Pulse in the foreseeable future.  I'm going to go ahead and close this issue for now.
