### ISSUE TITLE
Dropdown menu renders badly in Internet Explorer

### ISSUE THREAD

**Issue by jtexnl** [18F/pulse#160]
In IE9: 
![image](https://cloud.githubusercontent.com/assets/6758591/7887886/59d61814-0602-11e5-91ad-35483f86047a.png)

...and in Chrome: 
![image](https://cloud.githubusercontent.com/assets/6758591/7887894/6c9524d6-0602-11e5-95aa-2311b21007cc.png)

**Comment by konklone** [comment]
Updated the ticket name to reflect that this happens in IE9, IE10, and IE11.
