### ISSUE TITLE
add data records to gsa.gov/data.json 

### ISSUE THREAD

**Issue by gbinal** [18F/pulse#163]

**Comment by rebeccawilliams** [comment]
+1

**Comment by ErieMeyer** [comment]
+1

**Comment by konklone** [comment]
Yep, and see #72 for some more discussion. This is a priority, and it's in our Phase 1 Wrapup milestone so that we get it done before we call this round of work "done".

**Comment by gbinal** [comment]
This is in progress, though it's been slow going.

**Comment by gbinal** [comment]
Just to affirm, this happened.  

http://open.gsa.gov/data.json
