### ISSUE TITLE
Ensure Safari in Windows can change table size

### ISSUE THREAD

**Issue by konklone** [18F/pulse#168]
@jtexnl reports:

> When viewing the site with Safari from a Windows environment, the dropdown menu for setting table size was not visible at all. When I tried the same thing from an OSX environment, the issue was gone. Again, might be an anomaly, but probably worth double-checking.

**Comment by juliaelman** [comment]
Is Safari on Windows something we are needing to support?

**Comment by konklone** [comment]
Oh, I didn't realize it but I guess Apple [abandoned Safari for Windows](http://9to5mac.com/2012/07/25/apple-appears-to-currently-be-passing-on-safari-6-0-features-for-windows-pcs/) a few years back. So no, it's not.
