### ISSUE TITLE
Plan long run O&M work

### ISSUE THREAD

**Issue by gbinal** [18F/pulse#18]
Ensure how this will be paid for and maintained in 6, 12, 18, 36 months, etc.

**Comment by konklone** [comment]
@gbinal Can you break this down a little bit for me? What are the steps here?

**Comment by gbinal** [comment]
To clarify, I need to coordinate with OGP on eventually taking over the operations and maintenance of this site.  It'll likely be an FY'17 focus.

**Comment by gbinal** [comment]
This is an issue but one that is better addressed elsewhere.  I'm going to close for now.
