### ISSUE TITLE
Remaining 508 Issues 

### ISSUE THREAD

**Issue by gbinal** [18F/pulse#183]
- [ ] Remove tabbing ability from slide out menu when in desktop mode
- [ ] Add aria labeling to "Show ... entries"
- [ ] Add `focus` state to SSL Labs grade
- [ ] Pagination discussion resulted in the team deciding to move towards only using "Previous" and "Next" links.

**Comment by konklone** [comment]
What are the remaining issues here? @juliaelman

**Comment by juliaelman** [comment]
@konklone I added some checkboxes to the description of this issue to better lay out what is left to do. I'll circle back with @nickbristow on these and see if there is anything else that needs to be added.

**Comment by gbinal** [comment]
@nickbristow - With @juliaelman out of the office, are you able to let us know the severity of these four issues?

**Comment by nickbristow** [comment]
@gbinal they are still on the site, they aren't "major" issues. The site is still usable with AT, it would just be a better experience with these issues addressed.

**Comment by gbinal** [comment]
These have been addressed in later site updates.
