### ISSUE TITLE
Pluse expanders off by one pixel

### ISSUE THREAD

**Issue by KHarshawat** [18F/pulse#191]
The `+` in the expander buttons on the domain page is 1 pixel too high in the bubble. Please see the example screenshot below.

![image](https://cloud.githubusercontent.com/assets/6335546/7945660/37c860f6-0940-11e5-898e-abbfc5a649a8.png)

**Comment by gbinal** [comment]
Thanks, @KHarshawat.  We're balancing a number of priorities on the project and may not get to this, I'm afraid.  I'm going to go ahead and close for now.
