### ISSUE TITLE
Singleton website repos should have their URL metadata filled out for discoverability

### ISSUE THREAD

**Issue by jden** [18F/pulse#194]
For GitHub repos whose primary purpose is to run a single website (as opposed to, for example, a command-line tool, a software library, or a web app meant to be run in many separate deployments) the URL metadata should be filled in to link back to the website running the primary instance of the code.

GitHub doesn't let me pull request metadata, but this repo's URL should be https://pulse.cio.gov/

**Comment by konklone** [comment]
Done! We were only keeping it off the metadata until we had the blog post out, to give us a higher chance of surprising people. :)
