### ISSUE TITLE
Add ARIA, accessibility and/or 508 compliance stats!

### ISSUE THREAD

**Issue by JoshMock** [18F/pulse#195]
I'd love to see stats on how well our government's websites are doing with regards to accessibility. There are a [ton of tools](http://www.w3.org/WAI/ER/tools/) available to perform the analysis necessary.

**Comment by quepol** [comment]
+1 :exclamation:

**Comment by konklone** [comment]
@JoshMock Totally agree! A great place to start would be for someone to do such a scan now (you don't need to wait for pulse.cio.gov to do it) and start digging into the shape and reliability of the data. The devil is always in the details!

cc @adelevie @nickbristow

**Comment by andrewmaier** [comment]
+1 That would make Pule _very_ similar to a project I worked on for a major tech company a few years back.

**Comment by adelevie** [comment]
@nickbristow and I will be discussing this today. It's a feature we'd really like to land.

**Comment by adelevie** [comment]
Working on getting `pa11y` (accessibility) checks in the `site-inspector` gem: https://github.com/benbalter/site-inspector/pull/39

**Comment by JoshMock** [comment]
Awesome! Thanks @nickbristow, @adelevie and anyone else involved in this. Was gonna start fiddling with @konklone's suggestion this weekend but y'all beat me to it. :)

**Comment by konklone** [comment]
@JoshMock Well don't let the momentum deter you from adding more fuel to the fire! Hop on over to the pull request and help out. =)

**Comment by juliaelman** [comment]
@JoshMock +1 to what @konklone stated and am looking forward to seeing what you come up with :rocket:

**Comment by gbinal** [comment]
Just to update, this has been happening in the form of integrating pa11y scans.  I'm going to go ahead and close the issue.
