### ISSUE TITLE
site status 'alpha' -> 'beta'

### ISSUE THREAD

**Issue by gbinal** [18F/pulse#196]
Reviewing the [Project Stage Definitions](https://18f.gsa.gov/dashboard/stages/#alpha) we use for the [18F Dashboard](https://18f.gsa.gov/dashboard), I think that we passed from alpha to beta this week.

**Comment by gbinal** [comment]
Would be changed with this pull request - https://github.com/18F/pulse/pull/197

**Comment by juliaelman** [comment]
Merged!
