### ISSUE TITLE
More accurate assessment of HTTPS for Bad Host Name / URL redirects / certificate mismatch

### ISSUE THREAD

**Issue by shallbetter** [18F/pulse#207]
Some sites such as show up in Pulse HTTPS as not supporting HTTPS when they actually do.  Seems to be an issue with bad hostnames in the certificate.   iedison.gov and edison.gov redirect to sub-URLs not covered in TLD list (e.g. s-edison.info.nih.gov or https://public.era.nih.gov/iedison/).  These URLs do actually support and force HTTPS but are not showing up in pulse as supporting HTTPS.  tls.csv value in Valid HTTPS column says FALSE, but this is accurate but misleading.  Best practices would have the certificate valid for multiple domains.  Right now this error isn't available through the site.

**Comment by konklone** [comment]
iedison.gov and edison.gov, if accessed over HTTP, redirect to HTTPS websites, but the domains themselves don't support HTTPS. 

![screenshot from 2015-06-03 11 45 33](https://cloud.githubusercontent.com/assets/4592/7964525/28363068-09e6-11e5-9753-7dd7275c6e23.png)

As we [describe on our blog](https://18f.gsa.gov/2015/06/02/taking-the-pulse-of-the-federal-governments-web-presence/), when the error is an invalid hostname, we treat that as HTTPS being unsupported on the domain. If iedison.gov and edison.gov don't have a certificate valid for their hostname, they cannot be safely accessed over HTTPS, and so their redirects are insecure. We're evaluating the security of redirectors in addition to (and independently of) evaluating the security of the websites they redirect to.

I agree that this can cause confusion, but the goal here is for every .gov domain to support valid HTTPS (and strong HSTS), so this is the methodology we've got to stick with.

**Comment by shallbetter** [comment]
Its not about confusion to me, but more that there is a clear problem with HTTPS that needs to be fixed which isn't highlighted in some way.  This isn't rampant (20 domains show up with the problem), but the directive to reduce federal TLD is clearly the impetus.  There continue to be domains which have been in use and known to customers that are no longer being used as a way to reduce real estate.  The redirects assist the public.  

I guess the baseline assumption is that HTTPS will get to 100% so anything showing up as not supporting it will get fixed on way or another.  Moving on.
