### ISSUE TITLE
More and dynamic donuts please 

### ISSUE THREAD

**Issue by shallbetter** [18F/pulse#208]
Love the simplicity of the donut, but it would be great for these to reflect the currently displayed data instead of simply the overall status of one metric.  If I filter on an Agency, I'd like donut to show the agency status.  

It would also be interesting to see the other critical HTTPS stats as donuts as I drill down.

**Comment by konklone** [comment]
I'd love to make the donuts more dynamic. They are about as simple as can be at the moment. :) Leaving this ticket open so we can consider it for future iterations.

**Comment by gbinal** [comment]
This is a good idea, but in the ensuing period, we've decided to focus our limited resources on the functionality and scope of the site.  As a result, we have limited capacity for refactoring the design aspects.  That said, we accept pull requests!  So, please feel free to take a crack at it if you get inspired.  :)
