### ISSUE TITLE
Show hosting details cloud / outsource / in-sourced service

### ISSUE THREAD

**Issue by shallbetter** [18F/pulse#217]
whois information on endpoint ip could derive information on hosting provider to give a sense of the use of cloud providers vs in-sourced services

**Comment by konklone** [comment]
That's interesting. I encourage you to take the [.gov domain list](https://github.com/GSA/data/blob/gh-pages/dotgov-domains/2015-03-15-federal.csv) and run such a scan and tell us what you find.

**Comment by gbinal** [comment]
Thanks for the good idea - I've added this to [the list we keep of potential expansions to pulse](https://github.com/18F/pulse#ideas-for-later-versions) but am going to go ahead and close the issue in the meantime.  We're hoping to add more scans to pulse in FY'17 and will follow up here if this is chosen.  

Again, thanks for the great idea and please share any others.
