### ISSUE TITLE
Incomplete URL for TTB.gov

### ISSUE THREAD

**Issue by LChapman** [18F/pulse#220]
TTB.gov should link to www.ttb.gov. Right now it's trying to link to Http://ttb.gov, which of course doesn't work.

**Comment by konklone** [comment]
Hmm -- I appreciate the issue, but http://ttb.gov works fine for me, both directly from your link here, and from within Pulse. I'm closing the issue for now, but please re-open if you can isolate the issue further or provide more detail.

**Comment by LChapman** [comment]
When I click on the link, I get the Page Cannot Be Displayed message.  I’ll check with our IT guys to see what’s going on.

[cid:image004.jpg@01D0A428.8527A780]

Thanks,
Linda Chapman

**Comment by konklone** [comment]
Ah, okay -- I suspect it's how your office's internal DNS is configured. You could try visiting http://ttb.gov from a personal mobile phone on a 3G network, or from a personal computer on non-office WiFi, to see if this is the case.

**Comment by LChapman** [comment]
That’s it.  I can link to the site using my personal email account.  Thanks!
