### ISSUE TITLE
Visually indicate difference between bad and good result

### ISSUE THREAD

**Issue by konklone** [18F/pulse#229]
The first and most non-controversial thing that comes to mind is bolding the value in the table, if the result is the best result possible.

**Comment by juliaelman** [comment]
@konklone this probably needs some definition around what is considered "good" and "bad" too. 

On that note, we might also want to make sure to point folks with a lower score towards the guidance tabs to help them get a better understanding of how to raise their scores too.

**Comment by gbinal** [comment]
We've walked away from this some and I'm not sure that it's going to be a priority in the future.  I'm going to go ahead and close for now though feel free to reopen if desired.
