### ISSUE TITLE
Clicking on a domain shows a red minus icon that looks like it indicates "bad".

### ISSUE THREAD

**Issue by lgarron** [18F/pulse#253]
e.g. see whitehouse.gov in this screenshot:

![screen shot 2015-07-24 at 15 58 02](https://cloud.githubusercontent.com/assets/248078/8886311/e6fc1d10-321c-11e5-8fb0-da5b4fd5d800.png)

**Comment by konklone** [comment]
Taking this on as part of the current sprint to meet the pre-existing goal of linking to our new domain and agency landing pages.
