### ISSUE TITLE
produce mockups of subdomain page 

### ISSUE THREAD

**Issue by gbinal** [18F/pulse#264]

**Comment by xtine** [comment]
<img width="555" alt="screen shot 2015-08-11 at 5 52 26 pm" src="https://cloud.githubusercontent.com/assets/24054/9448579/493b2e5e-4a95-11e5-8aeb-32ebe7f2ef97.png">
First mockup of an idea I had for Agency/Subdomain listing

And then iterated on that idea:
![screen shot 2015-08-12 at 9 37 56 am](https://cloud.githubusercontent.com/assets/24054/9448587/56ef8b12-4a95-11e5-8310-d28ae5b27644.png)
