### ISSUE TITLE
produce mockups of an agency landing page

### ISSUE THREAD

**Issue by gbinal** [18F/pulse#265]

**Comment by xtine** [comment]
![agency page copy](https://cloud.githubusercontent.com/assets/24054/9529186/dd82441e-4cf0-11e5-8f19-61c6f13cb7a0.png)

**Comment by xtine** [comment]
![agency page copy](https://cloud.githubusercontent.com/assets/24054/9529227/039bea1a-4cf1-11e5-9c54-078b81319a16.png)
