### ISSUE TITLE
circulate subdomain list to cio community

### ISSUE THREAD

**Issue by gbinal** [18F/pulse#283]

**Comment by konklone** [comment]
This advanced quite far during Sprint 2, has been discussed among a subset of CIOs, and is scheduled to be sent out broadly to the CIO community on Monday.

**Comment by djharrity** [comment]
This list concerns me, I've seen it. Many sites are not for the public; for example there are more than 300+ email websites for employees. And countless others are remote access portals.

**Comment by konklone** [comment]
@djharrity Totally understood -- you're defintely not the only one to say that. This is something we're working through with the CIO community, and probably best handled among the rest of those email conversations. As far as meeting the goal of this specific ticket, we've distributed it, and can close the issue.
