### ISSUE TITLE
Mention SNI among other TLS nudges

### ISSUE THREAD

**Issue by konklone** [18F/pulse#292]
Requiring [SNI](https://https.cio.gov/sni/) can drastically reduce hosting costs for some agencies, and is considered a best practice generally as the world runs low on IPv4 addresses.

Requiring SNI cuts off IE+XP users, which is often a pretty small amount. We started requiring SNI for analytics.usa.gov, which drastically cut hosting costs on CloudFront.

There's a whole page on https.cio.gov to link to about it, and I think it'll be worth growing this out, or even blogging about.

**Comment by gbinal** [comment]
Still want to keep this open, @konklone?

**Comment by konklone** [comment]
I'm fine with closing it.
