### ISSUE TITLE
Restore auto-deploy process

### ISSUE THREAD

**Issue by konklone** [18F/pulse#313]
The staging and production deploy processes used to be automatic, but we disrupted that during the Flask transition. We need to restore this, and have the gunicorn processes properly daemonized, etc.

**Comment by gbinal** [comment]
@konklone - can you confirm if this is still outstanding?  It would seem to be resolved, right?

**Comment by konklone** [comment]
No, it's not. The site no longer auto-deploys when PRs are merged. But I think it's no longer a priority, and this can be closed.
