### ISSUE TITLE
New Homepage Design

### ISSUE THREAD

**Issue by xtine** [18F/pulse#342]
Mockups and front-end implementation of new homepage ideas.

**Comment by xtine** [comment]
@maya i got the front-end of top/graph portion of pulse-design-4 done in branch `homepage`, let me know if there's a section you want to work/improve on.

**Comment by gbinal** [comment]
Unfortunately, we weren't able to get to the homepage redesign this year, needing to focus on the promised functionality.  We can return to this in the next phase if desired.
