### ISSUE TITLE
Domain cjis.gov is missing from domain list

### ISSUE THREAD

**Issue by FixItDad** [18F/pulse#357]
The domain name for the Criminal Justice Information Systems Division of the FBI appears to be missing from the domain list.
I'm not sure if this was an oversight or intentional. Please consider adding this domain.

**Comment by konklone** [comment]
Domains can be missing from the list for a few different reasons. This project doesn't manage the .gov domain list, but I've relayed your comment to the .gov team, who can also be contacted at registrar@dotgov.gov.
