### ISSUE TITLE
Create/version a list of ineligible DAP domains

### ISSUE THREAD

**Issue by konklone** [18F/pulse#386]
With `fdms.gov` as the first example. It's a public executive branch domain, but not meant for the public and not under any obligation to support DAP.

We've known there was a subset of domains which didn't need to be eligible -- this would be a good time to catalog it. It could even make the DAP % go up!

cc @tdlowden

**Comment by tdlowden** [comment]
This is totally welcomed by DAP! We can use this list to alert those teams managing ineligible domains as well.

**Comment by konklone** [comment]
@tdlowden Do you already have a list, or any off the top of your head, that we should populate this list with?

**Comment by tdlowden** [comment]
some sites are tricky because they have both public and fed-only login sections. one example is ecpic.gov

**Comment by konklone** [comment]
I would say that if there's a section of the site that's eligible for DAP, we should keep them in the list. Getting them to implement DAP for the right pages is more of an internal program management concern, I think.

**Comment by tdlowden** [comment]
great point.

**Comment by konklone** [comment]
This was done in #401.
