### ISSUE TITLE
Finalize error categories

### ISSUE THREAD

**Issue by gbinal** [18F/pulse#394]
@nickbristow and @adelevie - I need you two to connect with @jtexnl and ensure you're all on the same page about the error categories and how they are defined.

**Comment by nickbristow** [comment]
@adelevie @jtexnl 
We just need to sit down and hash this out. 

Have time today?

**Comment by gbinal** [comment]
This is done.  

Color Contrast Errors - 1_4(contrast error)
Alt Tag Errors - 1_1(missing alt)
HTML/Attribute Errors - 4_1_2(missing anchor), 4_1_1(duplicate id)
Form Errors  - 1_3_1 (missing label) 1_3_1(missing legend)
Misc Errors - everything else
