### ISSUE TITLE
A11y order of operations

### ISSUE THREAD

**Issue by adelevie** [18F/pulse#406]
### First iteration:

- [ ] Host a11y json files in S3 temporarily (@adelevie and @jtexnl)
- [ ] Develop application code that reads and renders that data (@xtine) (By Domain, By Agency, Detailed Error Page)

- [ ] Deploy that new application code (@konklone and/or @xtine)

<hr />

### Second iteration:

- [ ] Get pa11y dependencies installed on EC2 (@konklone and @adelevie)
- [ ] Get Pulse code able to process a11y.csv (generated from domain-scan) (@adelevie)
- [ ] Deploy new Pulse code to EC2 (@konklone and @adelevie)
- [ ] Run a11y scan on EC2 (@konklone)

**Comment by gbinal** [comment]
We've moved past this and now are in the implementation phase of it.  Closing this for now.
