### ISSUE TITLE
Code for accessibility data wrangling

### ISSUE THREAD

**Issue by jtexnl** [18F/pulse#407]
`import csv
import re
import json

#Read in a11y.csv for errors
ally = []
with open('a11y.csv', 'rU') as infile:
    reader = csv.reader(infile)
    for row in reader:
        ally.append(row)

#Truncate the a11y file so that it's a bit more manageable. Need the domain name [0] and the principle [4]
main = []
for row in ally:
    main.append([row[0], row[4]])

#Read in domains.csv for agencies
domains = []
with open('domains.csv', 'rU') as infile:
    reader = csv.reader(infile)
    for row in reader:
        domains.append(row)

#Add the information on the agency [1] and branch [2]
for error in main:
    for domain in domains:
        if error[0] == domain[0].lower():
            error.append(domain[1])
            error.append(domain[2])

#Define the branches and add them to the main file
branches = {"Library of Congress":"Legislative","The Legislative Branch (Congress)":"Legislative",
"Government Printing Office":"Legislative","Congressional Office of Compliance":"Legislative",
"The Judicial Branch (Courts)":"Judicial"}

for row in main:
    if row[-1] in branches.keys():
        row.append(branches[row[-1]])
    else:
        row.append('Executive')

#Create truncated error type for categorization
for i in main:
    principle = i[1]
    pieces = re.split('.*(Guideline)', principle)
    shortened = pieces[-1]
    pieces = shortened.split('.')
    num = pieces[0]
    i.append(num)

#categorize the errors
errorCats = {'1_4':'Color Contrast Error', '1_1':'Alt Tag Error', '4_1':'HTML/Attribute Errors', '1_3':'Form Errors'}

#Add the error categories to main
for row in main:
    if row[-1] in errorCats.keys():
        row.append(errorCats[row[-1]])
    else:
        row.append('Other')

"""
Part 1: domains.json
{
     “agency": "General Services Administration",
     “branch": "executive",
     “canonical": "http://www.18f.gov",
     “domain": "18f.gov”,
     “errorlist”: {“color constrast errors”: 2, “alt tag errors”: 3},
     “errors”: 10,
     “warnings”: 30
}
"""

#create error counts and add the count to the main data
for row in domains[1:len(domains)]:
    if row[0].lower() in branches.keys():
        row.append(branches[row[0].lower()])
    else:
        row.append('Executive')

errorDictByDomain = {}
for row in main:
    if row[0] in errorDictByDomain:
        errorDictByDomain[row[0]] += 1
    else:
        errorDictByDomain[row[0]] = 1

for domain in domains[1:len(domains)]:
    try:
        domain.append(errorDictByDomain[row[0].lower()])
        subset = []
        for line in main:
            if line[0] == row[0].lower():
                subset.append(line)
        errorDict = {}
        for row in subset:
            if row[-1] in errorDict:
                errorDict[row[-1]] += 1
            else:
                errorDict[row[-1]] = 1
        domain.append(errorDict)
    except KeyError:
        continue

#add the base domain
canonicals = {}
for row in ally[1:len(ally)]:
    try:
        if row[0] in canonicals.keys():
            continue
        else:
            canonicals[row[0]] = row[1]
    except KeyError:
        continue

for domain in domains[1:len(domains)]:
    try:
        if domain[0] in canonicals.keys():
            domain.append('http://' + canonicals[domain[0].lower()])
        else:
            domain.append('http://' + domain[0].lower())
    except TypeError:
        continue

#form subset (pieces needed for the json file)
domainsSub = []
for row in domains[1:len(domains)]:
    domainsSub.append([row[2], row[5], row[-1], row[0].lower(), row[7], row[6]])

def getKey(item): 
    return item[3]

domainsSub = sorted(domainsSub, key = getKey)

dictList = []
for row in domainsSub:
    subDict = OrderedDict({})
    subDict['agency'] = row[0]
    subDict['branch'] = row[1]
    subDict['canonical'] = row[2]
    subDict['domain'] = row[3]
    subDict['errors'] = row[5]
    subDict['errorlist'] = row[4]
    dictList.append(subDict)

finalDict = {}
finalDict['data'] = dictList
with open('domains.json', 'w+') as outfile:
    json.dump(finalDict, outfile)`

**Comment by gbinal** [comment]
More easily seen here - https://gist.github.com/jtexnl/031d409977365e2c00823d2cb13b2135#file-pulsedatawrangling-py-L1
