### ISSUE TITLE
508 Issues from GSA

### ISSUE THREAD

**Issue by nickbristow** [18F/pulse#408]
We got a 508 report from GSA, here are the issues they found on the domain page. 

These should be fixed on all pages

- [ ]  Use empty alt tag on flag icon
- [ ] Multiple h1's used on the page
- [ ] First row in table with scope = row should be TH, not TD
- [ ] Table doesn't have a caption
- [ ]  Search box doesn't have explicit lable (label for= )
- [ ] use `onclick="document.getElementById('target').focus()"` on skip nav
- [ ] Tab links need to be programmed like tabs
- [ ] table breaks at 200% zoom
- [ ] Show 10|25|50 entries isn't keyboard accessible
- [ ] Loss of focus on checkboxes and column heading links
- [ ] banner needs `role="banner"`
- [ ] nav needs `role="nav"`
- [ ] Page needs `role="main"`
- [ ] Footer needs `role='contentinfo'`
- [ ] h1 should match page title

**Comment by gbinal** [comment]
I believe these are entirely or mostly done, but regardless, they appear to be surpassed by later work.
