### ISSUE TITLE
Settle on an order for the error categories 

### ISSUE THREAD

**Issue by gbinal** [18F/pulse#413]
The order of the categories on the [domains page](https://pulse.cio.gov/accessibility/domains/) and [an individual website error page](https://pulse.cio.gov/accessibility/domains/) are different.  I'm neutral as to what the order should be but we should make them the same order (the left most category on the former is the top on the latter).  

@jtexnl, @nickbristow, @adelevie - do any of you have thoughts or preferences about the order?  

----------------

An example (note the order of color contrast and html errors):

![screen shot 2016-04-06 at 8 16 28 am](https://cloud.githubusercontent.com/assets/633088/14316425/e61a39c6-fbd0-11e5-9f18-73c5513edc7f.png)

![screen shot 2016-04-06 at 8 16 39 am](https://cloud.githubusercontent.com/assets/633088/14316424/e6198436-fbd0-11e5-9771-e7cc574e41a2.png)

**Comment by nickbristow** [comment]
They should definitely be the same. I would say... 
- HTML/Attributes
- Color Contrast
- Form Errors
- Alt
- Other

**Comment by jtexnl** [comment]
I have no preference, so I'll go with what @nickbristow says here. I assume this is a change that will need to come on the data wrangling end, yeah?

**Comment by gbinal** [comment]
I'm not sure.  @xtine - is this a change that needs to happen on the data wrangling end or the coding end?  Is one or the other easier or more sustainable long-term?  

I'm not sure if it's intrinsically related but I noticed that the order of the error categories varies from domain to domain on the domains page.  For instance:  

![screen shot 2016-04-07 at 1 10 59 pm](https://cloud.githubusercontent.com/assets/633088/14360012/31ae2fae-fcc2-11e5-97dc-2bc30afaeccb.png)

**Comment by xtine** [comment]
If we want to follow a certain order (other than alphabetical), it would be a lot easier if it came from the data side.

**Comment by jtexnl** [comment]
I think we're in good shape here now. Current state of the code is [here](https://gist.github.com/jtexnl/031d409977365e2c00823d2cb13b2135). We can re-open if the ordering is still off. I went with alphabetical; it's the simplest way, and 'Other' remains at the end anyway (which was the intention of Nick's suggestion)
