### ISSUE TITLE
Sort order not working for columns with progress bars

### ISSUE THREAD

**Issue by rossettistone** [18F/pulse#414]
Visiting https://pulse.cio.gov/https/agencies/ on Chrome 49, clicking on the column headers (e.g. "Uses HTTPS") does not sort the rows below. Screenshot included here of the page with an active column sort on "Uses HTTPS" but the rows still unsorted.

<img width="994" alt="screen shot 2016-04-06 at 1 40 03 pm" src="https://cloud.githubusercontent.com/assets/1834981/14332695/89a7a712-fbff-11e5-8207-18321979a7b1.png">

**Comment by konklone** [comment]
Thanks for pointing this out. It's fixed in #415.

It's unfortunate that when I fixed this for one page in 7df7b463dc27b6e43e3c64d1226ca50549dc8445, I didn't think to fix it on the other...
