### ISSUE TITLE
ensure that anchor tags work on individual error pages 

### ISSUE THREAD

**Issue by gbinal** [18F/pulse#416]
When I click on an error category on the domains page, it's always taking me to the top of the individual error page.  I could be wrong but it seems like there aren't `ID=` or similar for the anchor tags to work.  

For instance:  https://pulse.cio.gov/accessibility/domain/aapi.gov#ColorContrastErrors

**Comment by xtine** [comment]
For some reason it's not working despite setting the appropriate ids... can someone double check that I didn't miss something? @adelevie @konklone @jtexnl 
<img width="1163" alt="screen shot 2016-04-13 at 7 07 21 pm" src="https://cloud.githubusercontent.com/assets/24054/14514129/17ff1882-01ab-11e6-901a-b0d186a23327.png">

**Comment by gbinal** [comment]
This appears to still be a problem.  https://staging.pulse.cio.gov/accessibility/domain/aapi.gov#ColorContrastErrors

**Comment by xtine** [comment]
PR needs to be merged and pushed: https://github.com/18F/pulse/pull/440
