### ISSUE TITLE
Test content to validate ruleset

### ISSUE THREAD

**Issue by normanbrobinson** [18F/pulse#417]
We need to identify a test harness or content to test the accessibility rules function properly.

I see that the rules applied are listed in https://github.com/springernature/pa11y/wiki/HTML-CodeSniffer-Rules and over at http://squizlabs.github.io/HTML_CodeSniffer/Standards/Section508/ - however I don't see any sample content to indicate the function is valid. Content that the program can run against to demonstrate it functions and detects the conditions properly. Ultimately a valid (should pass) and invalid (incorrectly coded) function is needed for each rule.

I'm aware of some of this outlined at a basic level in the HTML5.1 nightly, but do not know a definitive W3C project that provides a valid simple HTML example, and more complex HTML+CSS+JavaScript examples, or further parsing in each ruleset category. E.g., Error: Img element missing an alt attribute. Use the alt attribute to specify a short text alternative. (Section508.A.Img.MissingAlt) might fail, however if TITLE and or Figure was used, content might pass.

Any suggestions? Should I put this in the pa11y project?

**Comment by gbinal** [comment]
We're doing a pretty transparent passthrough to the scanning methodology of `pa11y`/`HTML_CodeSniffer`, so I'm going to close this out for now.  Thanks.
