### ISSUE TITLE
Sorting doesn't work on https://pulse.cio.gov/https/agencies/

### ISSUE THREAD

**Issue by alex** [18F/pulse#423]
Specifically, pressing any of the "Uses HTTPS", "Enforces HTTPS", "Strict Transport Security (HSTS)", or "SSL Labs (A- or higher)" things toggles the icon, but doesn't actually sort the table

**Comment by konklone** [comment]
I filed a PR for this a while back but it didn't get reviewed, #415. Merged and deployed.
