### ISSUE TITLE
Add scan for SPF records?

### ISSUE THREAD

**Issue by alex** [18F/pulse#424]
Specifically any domain which has an `MX` DNS record should be checked to see if there's an SPF `TXT` record, an email best practice to reduce fraudulent mail. This is particularly important for `.gov` domains because of the implied trust in that TLD.

cc @liyanchang

**Comment by ab** [comment]
👍 

And while we're at it, checking for `DMARC` `TXT` records would be great, since those are even more important for email authenticity.

For example, gov.uk publishes a strict p=reject policy:

```
$ dig +short _dmarc.gov.uk TXT
"v=DMARC1\;p=reject\;sp=none\;adkim=s\;aspf=s\;fo=1\;rua=mailto:dmarc-rua@dmarc.service.gov.uk\;ruf=mailto:dmarc-ruf@dmarc.service.gov.uk"
```

**Comment by gbinal** [comment]
Thanks for the good idea - I've added this to [the list we keep of potential expansions to pulse](https://github.com/18F/pulse#ideas-for-later-versions) but am going to go ahead and close the issue in the meantime.  We're hoping to add more scans to pulse in FY'17 and will follow up here if this is chosen.  

Again, thanks for the great idea and please share any others.
