### ISSUE TITLE
API for accessing pulse data

### ISSUE THREAD

**Issue by alex** [18F/pulse#425]
(This seemed slightly different from #9)

Specific queries I'd love to be able to run:

- [ ] All domains with HTTPS, ordered by negative SSL Labs score
- [ ] Last updated date for the dataset

**Comment by konklone** [comment]
There is an officially supported RSS feed of scan dates, which you can also use to get the latest scan/report **date** (but not the time):

* https://pulse.cio.gov/data/reports/feed/

While we don't have an API that does sorting for you, this officially linked CSV has the HTTPS results, which you can sort by SSL Labs grade easily enough:

* https://pulse.cio.gov/data/domains/https.csv

I'd like to do more and provide a proper API, especially as things get more sophisticated. We probably have some more surgery to do before that's reasonable, but as you can see above, the data is there at official URLs.

Will these suit your needs?

Also, there is an unofficial undocumented API where we publish the latest scan metadata in machine-readable form, which contains the last updated date _and_ time:

* https://s3.amazonaws.com/pulse.cio.gov/live/scan/meta.json

**Comment by alex** [comment]
I can probably build what I'd like out of these; I think it'd be nice if
the parts that were considered stable were documented so others can build
on them.

On Sun, May 1, 2016 at 6:48 PM, Eric Mill <notifications@github.com> wrote:

> There is an officially supported RSS feed of scan dates, which you can
> also use to get the latest scan/report *date* (but not the time):
>
>    - https://pulse.cio.gov/data/reports/feed/
>
> While we don't have an API that does sorting for you, this officially
> linked CSV has the HTTPS results, which you can sort by SSL Labs grade
> easily enough:
>
>    - https://pulse.cio.gov/data/domains/https.csv
>
> I'd like to do more and provide a proper API, especially as things get
> more sophisticated. We probably have some more surgery to do before that's
> reasonable, but as you can see above, the data is there at official URLs.
>
> Will these suit your needs?
>
> Also, there is an unofficial undocumented API where we publish the latest
> scan metadata in machine-readable form, which contains the last updated
> date *and* time:
>
>    - https://s3.amazonaws.com/pulse.cio.gov/live/scan/meta.json
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/pulse/issues/425#issuecomment-216079072>
>



-- 
"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: D1B3 ADC0 E023 8CA6

**Comment by konklone** [comment]
Yeah, we need a `/data/` page, a ticket I've opened in #426. (You can at least currently see the CSV [linked to from the top of the domain list](https://pulse.cio.gov/https/domains/).)
