### ISSUE TITLE
training.fema.gov

### ISSUE THREAD

**Issue by FEMAMarkMiller** [18F/pulse#430]
Hello,

I was reviewing your stats on pulse.cio.gov and noticed that training.fema.gov is not represented there under Department of Homeland Security. We are a FEMA organization, much like firstrespondertraining.gov. Also, www.usfa.fema.gov is not represented either. Just an FYI.

Mark

**Comment by konklone** [comment]
Hi Mark, you are right -- Pulse doesn't have any subdomains listed, only second-level domains. Do you have a list of subdomains FEMA operates that you'd like to see on Pulse?

**Comment by FEMAMarkMiller** [comment]
Hi Eric,

Just the 2 I mentioned. They are completely separate sites from FEMA.gov. FYI, firstrespondertraining.gov is a FEMA subdomain.

https://training.fema.gov/

https://www.usfa.fema.gov/

Thanks,

---
Mark Miller
IT Specialist, Sr. Webmaster
DHS, FEMA, NPD, NTED, NETC
Emergency Management Institute
Superintendent’s Business Office
16825 S. Seton Ave, E114A
Emmitsburg, MD 21727

Phone: 301-447-1479
iFEMA: 301-943-4243
FAX: 301-447-1112
Web: http://training.fema.gov/EMI/

FEMA’s mission is to support our citizens and first responders to ensure that as a nation we work together to build, sustain, and improve our capability to prepare for, protect against, respond to, recover from, and mitigate all hazards.

DHS Mission Statement: “With honor and integrity, we will safeguard the American people, our homeland, and our values.”

For OFFICIAL USE ONLY - This email and attached files may contain Privacy Sensitive information.  Any misuse or unauthorized disclosure may result in both civil and criminal penalties.  If you received this document in error, please notify me at the above phone number and destroy the document immediately in accordance with Privacy Act procedures.

[Description: cid:image001.jpg@01CA2CAE.E5F8CD20]

**Comment by gbinal** [comment]
Hi folks - 

Unfortunately, @konklone is right - we would like to expand the scanning to the subdomain level but aren't there yet.  We'll want to do that in a sustainable way and Issue #27 is the prerequisite that we'll need to fill in order to do that.  I'm going to close this in the meantime and leave #27 open with the hopes that we can do this sooner rather than later.
