### ISSUE TITLE
HHS domain, "BeTobaccoFree.gov" incorrectly labeled as non-compliant

### ISSUE THREAD

**Issue by SamBronson** [18F/pulse#432]
BeTobaccoFree.gov actually redirects to BeTobaccoFree.hhs.gov and is DAP compliant.  When possible, please remove BeTobaccoFree.gov as a separate domain.

Thanks.

**Comment by konklone** [comment]
Hi Sam - betobaccofree.gov isn't present on the DAP dashboard:

https://pulse.cio.gov/analytics/domains/#q=tobacco

It is measured for HTTPS, but not DAP adoption.

**Comment by SamBronson** [comment]
Sorry; mistake.  

Thanks, Eric.
