### ISSUE TITLE
Issues reading the expandable table with screen reader

### ISSUE THREAD

**Issue by nickbristow** [18F/pulse#441]
Its been reported that when reading the table, the expansion functionality isn't read to the user. 

This most likely occurs because of the way its coded. We have them set as tabindex='0' they might need to be made into real buttons.

**Comment by gbinal** [comment]
@nickbristow - was this addressed by our later work?

**Comment by konklone** [comment]
@gbinal @nickbristow We could take the work I did in #518 and port it to the a11y table, if appropriate, which might fix this issue.

**Comment by nickbristow** [comment]
@gbinal This should be fine now, closing.
