### ISSUE TITLE
Enable compression for text assets

### ISSUE THREAD

**Issue by anand-bhat** [18F/pulse#447]
While pulse.cio.gov appears to be using GZIP compression for html and css, it does not compress js, json and csv files. Compressing js and json resources will be very beneficial as some js (utils.js, domains.js, agencies.js -- timestamp in resource) and all json resources (no caching headers) are refetched every time a page is viewed.

When checked with https://developers.google.com/speed/pagespeed/insights/,

For https://pulse.cio.gov/: 230.1KB (64%) reduction
![image](https://cloud.githubusercontent.com/assets/7332442/16348504/8fb96f1e-3a70-11e6-8e31-059d004e9124.png)

For https://pulse.cio.gov/https/domains/: 648.5KB (80%) reduction
![image](https://cloud.githubusercontent.com/assets/7332442/16348595/24ab9f66-3a71-11e6-9cf4-7c7c59c2a3ac.png)

For https://pulse.cio.gov/https/agencies/: 254.9KB (66%) reduction
![image](https://cloud.githubusercontent.com/assets/7332442/16348563/e9edb0bc-3a70-11e6-8c07-536443f83de3.png)

**Comment by konklone** [comment]
This is resolved. (We needed to add `application/javascript` to the list of `gzip_types` in nginx.) Thanks for pointing it out!

**Comment by anand-bhat** [comment]
Thanks! Any plans for compressing the json (`application/json`) resources? The savings for https.json would be pretty large (raw 450.3 KB, if compressed ~ 29 KB)

**Comment by konklone** [comment]
Good eye - I'll take a look at this.

**Comment by konklone** [comment]
Done! I don't see any more targets for compression, but let me know if I'm missing something. Thank you!

**Comment by anand-bhat** [comment]
Looks good! The only thing I can find that would benefit from text compression is Content-Type: text/csv for file downloads such as https://pulse.cio.gov/data/domains/https.csv. Considering this doesn't happen on page load, it'd think it is low priority.

Thanks! :beers:

**Comment by konklone** [comment]
Adding `text/csv` was easy enough, done.
