### ISSUE TITLE
Fix duplicate HSTS header

### ISSUE THREAD

**Issue by anand-bhat** [18F/pulse#448]
pulse.cio.gov sends two HSTS header with every response.

![image](https://cloud.githubusercontent.com/assets/7332442/16349303/ba3b7372-3a75-11e6-86a7-8a2cf86ad967.png)
![image](https://cloud.githubusercontent.com/assets/7332442/16349310/c43d9292-3a75-11e6-9bfe-54feed2f710d.png)

**Comment by konklone** [comment]
This is fixed -- thanks for pointing it out.
