### ISSUE TITLE
create a /data page

### ISSUE THREAD

**Issue by gbinal** [18F/pulse#449]
https://pulse.cio.gov/data would be a good page to have going forward.

**Comment by gbinal** [comment]
* HTTPS scan data downloads - https://pulse.cio.gov/data/domains/https.csv
* DAP scan data downloads - https://pulse.cio.gov/data/domains/analytics.csv
* Domain Scan data downloads - https://s3.amazonaws.com/pulse.cio.gov/live/scan/inspect.csv

**Comment by gbinal** [comment]
https://staging.pulse.cio.gov/static/data/tables/accessibility/a11y.json
https://staging.pulse.cio.gov/static/data/tables/accessibility/agencies.json
https://staging.pulse.cio.gov/static/data/tables/accessibility/domains.json

**Comment by gbinal** [comment]
Note also the urls on https://github.com/18F/pulse/issues/425

**Comment by gbinal** [comment]
@konklone - game to create the page as a shell?  I tried but wasn't sure how to navigate the URL structure since there is a data folder.

I'm happy to follow up and populate if helpful.   

It'd be great to be to include an MVP of this in the 8-24 push.

**Comment by gbinal** [comment]
Rock.  We've got a placeholder for this now [here](https://github.com/18F/pulse/blob/data-page/templates/data.html) (screenshot below).  

![screenshot from 2016-08-24 00-24-49](https://cloud.githubusercontent.com/assets/633088/17932765/862591be-69df-11e6-8c18-7306aac76fb0.png)

**Comment by gbinal** [comment]
Here's the outline I've got for the pulse.cio.gov/data page:  

## Download the Data

Pulse is a project of the General Services Administration that measures how U.S. government domains are following best practices for federal websites.

Pulse is also an experiment built on automated tools, and is probably not perfect. Pulse measures domains over the public internet using open source tools, and its results can be reviewed by anyone.

### Site Wide

* Domain Inspect Results  ([CSV](https://s3.amazonaws.com/pulse.cio.gov/live/scan/inspect.csv))

### HTTPS

* HTTPS Scan Results ([CSV](https://pulse.cio.gov/data/domains/https.csv))

### Digital Analytics Program 

* Scan Data ([CSV](https://pulse.cio.gov/data/domains/analytics.csv))

### Accessibility 

* Individual Error Results (CSV)
* Individual Error Results ([JSON](https://staging.pulse.cio.gov/static/data/tables/accessibility/a11y.json))
* Domain-Level Results ([JSON](https://staging.pulse.cio.gov/static/data/tables/accessibility/domains.json))
* Agency-Level Results ([JSON](https://staging.pulse.cio.gov/static/data/tables/accessibility/agencies.json))

**Comment by gbinal** [comment]
We're getting a first pass of this up, with https://github.com/18F/pulse/pull/597.  

Other datafiles to potentially add:  
* https://s3.amazonaws.com/pulse.cio.gov/live/scan/analytics.csv
* https://s3.amazonaws.com/pulse.cio.gov/live/scan/pshtt.csv
* https://s3.amazonaws.com/pulse.cio.gov/live/scan/tls.csv
* https://s3.amazonaws.com/pulse.cio.gov/live/scan/meta.json
* https://s3.amazonaws.com/pulse.cio.gov/live/db/db.json

**Comment by konklone** [comment]
Not db.json. That's the actual database -- it's published for our own convenience reasons (you can easily download it to sync an environment) but is not at all convenient or designed for the public.

**Comment by gbinal** [comment]
Roger that.  I'll strike it through.

**Comment by gbinal** [comment]
[This is done](https://pulse.app.cloud.gov/data/).  There's more to do (linking it from more places, adding further links, but this issue can be closed for now.
