### ISSUE TITLE
push a11y section to *staging* 

### ISSUE THREAD

**Issue by gbinal** [18F/pulse#474]
Should be done Friday COB.  

And we'll leave off of the nav bar for now.

**Comment by konklone** [comment]
I'm on vacation Friday, in Las Vegas. Let me know if we need to coordinate on something around this.

**Comment by gbinal** [comment]
Thanks for the heads up - Could we coordinate a push either Friday COB (anytime is fine) or over the weekend?

**Comment by konklone** [comment]
We can do that - easiest to coordinate on Slack, but yes, I'm comfortable committing to a deploy between Friday and Sunday at some point.

**Comment by gbinal** [comment]
Important update - these should go to staging only and not production, @konklone.  Thanks, folks.
