### ISSUE TITLE
refresh https and dap scans

### ISSUE THREAD

**Issue by gbinal** [18F/pulse#490]
@konklone - there'll be a good bit more attention to our scanning process after 8/22, so it'd be good to make sure those re-run in advance of them.

**Comment by konklone** [comment]
@gbinal These get refreshed every week, automatically. If I'm missing something, please re-open.

**Comment by gbinal** [comment]
Ah - my apologies.  I've gone too far down the rabbit hole on this one and had forgotten that the dates would be different on staging than on production.  

Thanks and sorry for the bother.
