### ISSUE TITLE
Clear cache and request for rerun scan on site

### ISSUE THREAD

**Issue by Nala0704** [18F/pulse#492]
Hello.  Is it possible for you to clear cache for the tool and rescan the cdc.gov site again?  We think it is showing previous codes that we have changed. Please advise.  You may contact me at phunter@cdc.gov.

**Comment by gbinal** [comment]
Hi @Nala0704 - to confirm, are you referring to the HTTPS review?

**Comment by Nala0704** [comment]
Hello.  Yes, I think I am referring to the HTTPS review.  It’s the scan that GSA ran on August 8, 2016 and will run again on August 22, 2016.  Is it the same thing?  Please advise.

Thanks,

Pauline D. Hunter, MA, PMP
Health Communications Specialist
Digital Media Branch
Division of Public Affairs
Office of the Associate Director for Communication
Centers for Disease Control and Prevention (CDC)
Email: phunter@cdc.gov

**Comment by konklone** [comment]
Hi @Nala0704 - the scan runs weekly, so is set to run again on Thursday, with updated results showing Friday night (night of the 12th). Can you wait the few days for those results? If you have an internal deadline of some sort which a very rapid update would serve, we can make an exception to support your transition efforts. However, it does take extra effort on our part, so if you can wait until Friday night, that would be ideal.

**Comment by konklone** [comment]
@Nala0704 Also, right now pulse.cio.gov shows that cdc.gov is using HTTPS, but not enforcing it or using HSTS. I examined (just now) how cdc.gov behaves, and I think a rescan would not change what Pulse is currently showing.

Right now:

* http://cdc.gov uses a 301 redirect to http://www.cdc.gov.
* http://www.cdc.gov works, and **does not redirect** to HTTPS.
* https://cdc.gov works (but has a misconfigured certificate chain, which works in my browser but breaks in curl) and returns a 404. However, my browser redirects to https://www.cdc.gov. No HSTS header.
* https://www.cdc.gov works. No HSTS header.

So this amounts to cdc.gov supporting HTTPS, but not enforcing it, and not supporting HSTS. That's what pulse.cio.gov shows now, so a re-scan wouldn't change anything.

**Comment by Nala0704** [comment]
Hi Eric,

Is this the scan that GSA is running on .gov sites?   The current scan is still showing the codes from a previous scan.  It does not reflect the updated codes on the site.  Please advise.


Thanks,

Pauline D. Hunter, MA, PMP
Health Communications Specialist
Digital Media Branch
Division of Public Affairs
Office of the Associate Director for Communication
Centers for Disease Control and Prevention (CDC)
Email: phunter@cdc.gov<mailto:phunter@cdc.gov>

**Comment by konklone** [comment]
> Is this the scan that GSA is running on .gov sites?   The current scan is still showing the codes from a previous scan.  It does not reflect the updated codes on the site.  Please advise.

@Nala0704 I just advised. :) I went and measured cdc.gov's behavior directly, myself, yesterday, and verified that what Pulse indicates does reflect cdc.gov's configuration.

@Nala0704 It might be better to do this over email, so as not to bombard folks watching this open source project. You can email pulse@cio.gov, CC-ing anyone on your team who is responsible for administering cdc.gov's network configuration, and I'm happy to assist.

**Comment by konklone** [comment]
I locked the issue to direct the conversation to email -- @Nala0704, the right address is pulse@cio.gov, which goes right to me.
