### ISSUE TITLE
average errors off on the agency tab

### ISSUE THREAD

**Issue by gbinal** [18F/pulse#505]
Something appears to be off in how we're calculating the total errors and average errors for agencies.  

As a reviewer kindly pointed out, [there are errors reported for some DOD domains](https://staging.pulse.cio.gov/accessibility/domains/#q=department%20of%20defense), yet [on the agency tab](https://staging.pulse.cio.gov/accessibility/agencies/#q=department%20of%20defense), there's zeros across the board.  

@nickbristow - any idea what might be up?

**Comment by gbinal** [comment]
I've confirmed this with a couple other agencies, too, so it's an endemic issue.  

I'd confirmed the averages and totals was working correctly about a month ago, so something is off since then.  We'll be looking at this carefully and documenting each step in the [next scan](https://github.com/18F/pulse/issues/477) later this week

**Comment by nickbristow** [comment]
@gbinal i have some idea, we need to update how the initial scan is done to get a more accurate list of which domains belong to which agencies.

**Comment by gbinal** [comment]
This is addressed by #507.
