### ISSUE TITLE
push site updates to staging 

### ISSUE THREAD

**Issue by gbinal** [18F/pulse#508]
As part of #477.

**Comment by konklone** [comment]
It's probably cleaner to assign a PR to me once it's merged, and note that a deploy is requested.

**Comment by gbinal** [comment]
Roger that.

**Comment by gbinal** [comment]
Included in this push: 
* Fixes the a11y error total/averages being off - https://github.com/18F/pulse/issues/505
* Makes the 'What is Measured' material on the a11y guidance page consistent and more visible - #495, #497
* Adds section 1.4.3 (color contrast) to the WCAG/508 mapping on the guidance page - https://github.com/18F/pulse/pull/500

We're still working on and will plan to push to the staging site next week: 
* removing the judicial and legislative domains - https://github.com/18F/pulse/issues/501
* removing redirecting urls - https://github.com/18F/pulse/issues/502
* updating the scan date on the high level a11y pages - https://github.com/18F/pulse/issues/488 (the earlier fix addressed it on the individual domain pages)
* A /data page - https://github.com/18F/pulse/issues/449
* Download link on the a11y domains page - https://github.com/18F/pulse/issues/509
* Assorted non-critical 508 suggestions - https://github.com/18F/pulse/issues/511
