### ISSUE TITLE
Scope out cloud resource expenses over the long haul 

### ISSUE THREAD

**Issue by gbinal** [18F/pulse#52]

**Comment by konklone** [comment]
@gbinal Can you make this a bit more concrete? Is this a document that need to be written somewhere? Is it part of sprint 2?

**Comment by gbinal** [comment]
Sure.  

At issue is scoping out the non-people costs of this project.  In other words, how much AWS and any other cloud infrastructure we need costs.  

It's less that it needs to be an artifact and more about just wanting to make sure we have budgeted appropriately.  In other words, that we know how long we have funding to pay these costs.  

This doesn't have to be a part of sprint 2 since I believe we are still very, very inexpensive.  But I'd say let's include it in sprint 3.

**Comment by konklone** [comment]
Thank you -- that wasn't obvious from the title, and I'd either missed or forgotten it from sprint planning.

Nothing from sprint 2 to 3 _should_ change our infrastructure costs. However, we've not formally tallied up what those are. This task is on you and me to figure out past and present costs.

**Comment by gbinal** [comment]
this is done
