### ISSUE TITLE
donut charts went dark

### ISSUE THREAD

**Issue by gbinal** [18F/pulse#524]
![screen shot 2016-08-25 at 4 26 12 am](https://cloud.githubusercontent.com/assets/633088/17961892/27e1ccc4-6a7c-11e6-97a4-0bc4a9e0e306.png)

![screen shot 2016-08-25 at 4 26 19 am](https://cloud.githubusercontent.com/assets/633088/17961895/2bdab76e-6a7c-11e6-8320-a505a28a9d39.png)

**Comment by gbinal** [comment]
Might this be from https://github.com/18F/pulse/commit/837589b1b88f933ed04eac210e48ee3ffbf9aa83 ?

**Comment by konklone** [comment]
Something got out of sync between the production DB and the production code. I've reverted the production code to what it was on Monday (before I merged some PRs), and the production data to what it was on Saturday (right after the least weekly scan). I'll consider the production code frozen (and won't merge any PRs to `production` or do production deploys) until I can diagnose the root issue.
