### ISSUE TITLE
`by agency` tab on DAP section is missing data

### ISSUE THREAD

**Issue by gbinal** [18F/pulse#525]
On https://pulse.cio.gov/analytics/agencies/ - 

![screen shot 2016-08-25 at 4 29 59 am](https://cloud.githubusercontent.com/assets/633088/17961981/9c00df46-6a7c-11e6-94d8-fd90b49e4136.png)

I've checked and this isn't happening for any of the tabs on other sections.

**Comment by konklone** [comment]
https://github.com/18F/pulse/issues/524#issuecomment-242356545
