### ISSUE TITLE
Change a11y section name 

### ISSUE THREAD

**Issue by gbinal** [18F/pulse#535]
From `Accessibility` to `Universal Design and Access Module`

**Comment by gbinal** [comment]
@smarina04 and @rcbaker2 - I just want to throw out that this would be a pretty big step back in plain language and user-friendliness.  

It's an important benefit that someone arriving at the site be able to understand at a glance what this section is about.  I fear that if you go from:

![screen shot 2016-09-06 at 10 41 52 am](https://cloud.githubusercontent.com/assets/633088/18278082/c573313e-741e-11e6-92a7-4724f0e18223.png)

to: 

![screen shot 2016-09-06 at 10 42 44 am](https://cloud.githubusercontent.com/assets/633088/18278091/cc4b126a-741e-11e6-897c-fbc44b6903cd.png)

You'll be making the section less intuitive and more confusing out of the box.  If you ask someone looking at the first to make an initial guess as to what this section is about, they'd rightly guess accessibility issues.  With the renamed section, I think you'll find that the vast majority of users would not know what the section is about and instead would first ask _"What is the Universal Design and Access Module?"_, followed by _"And do I care?"_.  

It's the natural tendency in government to add more words to further couch something and make it feel safer for the product owner, right?  But user-centered design would have us instead ask how the experience is for users and maximize for them.  Keeping the section name as is would seem to benefit users and would keep the site easier to read and understand.

**Comment by normanbrobinson** [comment]
I recommended Universal Access and Design Module, however will disagree with you on it being a leap back. I interviewed a few people unrelated to the effort and they all thought the accessibility "had something to do with people with disabilities" and the "Universal Design" received more comments about actually designing and developing. Inclusive & Universal Design patterns is the outcome of the testing.

It should also be mentioned that there is a very specific concern with accessibility being defined through design standards under Section 508 (as in we have to with legal implications; it isn't optional or best practice's nice to have) and de facto standards of WCAG (best practices, nice to have, however no one files a legal complaint or goes to court unless detailed requirements are solicited in specific technical requirements in the contract). 

Also, accessibility is a term of art used to describe the technical compliance of IT products and services as well as usability by people with disabilities and interoperability with assistive technologies.

I wouldn't mind seeing it play out and doing further research. The most important part is that the automated testing works and is accurately reporting in a usable way.

**Comment by gbinal** [comment]
This is done by https://github.com/18F/pulse/commit/039e810851d4172af98df453e0b5aa4c1d92f326.  

One further question to clarify, I recommend that when we add in this section to the nav bar, it still say Accessibility.  As you'll note with the other sections, it's normal in this website to have short, clear text in the nav bar with the longer, more clear section name once you arrive there.

**Comment by gbinal** [comment]
This is ready to close.

**Comment by rcbaker2** [comment]
Based on DOJ feedback we may need to change this back to Accessibility, but
not for plain language reasons.

Robert Baker, PMP

Senior Accessibility Strategist -

ICT Public Policy & Program Management

Office of Government-Wide Policy

General Services Administration

robertc.baker@gsa.gov

202 705 5241

**Comment by gbinal** [comment]
It's been decided to roll this back...

**Comment by gbinal** [comment]
PR for this is https://github.com/18F/pulse/pull/558

**Comment by gbinal** [comment]
Done
