### ISSUE TITLE
the canonical field in the a11y domains.json file needs to be a full url

### ISSUE THREAD

**Issue by gbinal** [18F/pulse#565]
otherwise it causes https://github.com/18F/pulse/issues/563

**Comment by konklone** [comment]
Done.

**Comment by konklone** [comment]
Done.

**Comment by konklone** [comment]
Oh, I see this is meant to track the long-term fix, sorry.

**Comment by gbinal** [comment]
I believe this is no longer an issue and can be closed.

**Comment by gbinal** [comment]
Actually, it's still outstanding and requires a manual edit each time.

**Comment by konklone** [comment]
Fixed in #115.
