### ISSUE TITLE
Bug with missing image on GSA.gov

### ISSUE THREAD

**Issue by davidstenger** [18F/pulse#580]
After talking to Patrick about the GSA.gov site he pointed out that the context is getting cut off and you can't see the entire message. We can tell if this is a bug in the tool or if they really do have an issue with an image.

Missing Image Descriptions (1)
WCAG2AA.Principle1.Guideline1_1.1_1_1.H37
Selector: html > body > img
Context: <img src="https://www.pages04.net/WTS/event.jpeg?accesskey=3abe81a-13674a64302-b72427ac28f4177bd55290ce12678282&amp;v=1.28&amp;isNewSession=1&amp;type=pageview&amp;isNewVisitor=1&amp;sessionGUID=60e1c313-e265-c744-425c-13802ab9e219&amp;webSyncID=bdb6...
Description: Img element missing an alt attribute. Use the alt attribute to specify a short text alternative.

**Comment by gbinal** [comment]
The source of this has been identified and the most recent scan addressed the problem.  

This is actually a legitimate error, but [for a different site](https://staging.pulse.cio.gov/accessibility/domain/presidentialserviceawards.gov#HTMLAttributeErrors) - presidentialserviceawards.gov.  A glance at [the site's source code](view-source:https://www.presidentialserviceawards.gov/) shows the image at issue.  

As near as I can tell, in the earlier scan, my manual processing of the error report caused the error details for this to be pasted multiple times with other domains.  I believe I know when it happened and am on the lookout to keep it from recurring.
