### ISSUE TITLE
Research if plain language has any underlying data we could use

### ISSUE THREAD

**Issue by gbinal** [18F/pulse#594]

**Comment by normanbrobinson** [comment]
From a programmatic view, one probably wants to use the readability score or choose one of the specific algorithms promote that into a score. 

1. [https://github.com/masukomi/ar90-readability](https://github.com/masukomi/ar90-readability) (Apache 2.0 licensed with ports in a few languages)
2. [https://github.com/wimmuskee/readability-score](https://github.com/wimmuskee/readability-score) (GPL-2 in python)

**Comment by gbinal** [comment]
Thanks, @normanbrobinson!

**Comment by gbinal** [comment]
The decision was made to develop a customer satisfaction/3rd party services scan for the 4th section instead.  Thanks for the feedback though, @normanbrobinson.  I'm going to add a link to your notes in our [list of ideas](https://github.com/18F/pulse/blob/master/docs/other-sections.md) for other sections to build in the future.  

I'll go ahead and close this for now, though.  Thanks again.
