### ISSUE TITLE
"SSL Labs Grade" column not showing anything for any domain/agency on pulse.cio.gov

### ISSUE THREAD

**Issue by StephenHolliday** [18F/pulse#599]
While I'm specifically interested in having my domain's, bea.gov, SSL labs grade show up, I do not see any of the SSL Labs grades showing up on the pulse.cio.gov website.  Is this normal?  How can I get my own domain's SSL Labs grade to show up?

**Comment by konklone** [comment]
We've moved away from SSL Labs grades in Pulse.
