### ISSUE TITLE
create network diagram

### ISSUE THREAD

**Issue by gbinal** [18F/pulse#617]

**Comment by gbinal** [comment]
![img_20170216_105524](https://cloud.githubusercontent.com/assets/633088/23028953/e02e5204-f436-11e6-9327-0cddf32db979.jpg)

**Comment by konklone** [comment]
Note that https://github.com/18F/pulse/pull/651 changed this network diagram a bit by adding auto-deploy. There's now a connection from the scanning server to the Cloud.gov API to initiate automatic deploys. (The `Dev. Laptop` element is now optional, but also still used to initiate deploys sometime -- whether that needs to be in the network diagram is not obvious to me.)
