### ISSUE TITLE
Refine code for 3rd party services scanning 

### ISSUE THREAD

**Issue by gbinal** [18F/pulse#639]
https://github.com/18F/domain-scan/pull/107 is a baller start.  We'll need to refine it in order to use it.

**Comment by gbinal** [comment]
We next need to take the [first pass](https://github.com/18F/domain-scan/pull/107) that @konklone did at a scanner for 3rd party services, get it running again, and further refine it.  

Namely, we should figure out how to refine its outputs so that they generate [data files](https://github.com/18F/pulse/issues/657) that can then support the proposed functionality for the new section.  

The code then also needs to be amenable to hosting and automating in cloud.gov

**Comment by konklone** [comment]
> The code then also needs to be amenable to hosting and automating in cloud.gov

Just so it's clear, this isn't really specific to the third party services scanner, I don't think. It's the whole domain-scan tool and how it interfaces with the Pulse application layer.

**Comment by gbinal** [comment]
Done.
