### ISSUE TITLE
User Interviews with CIO or other stakeholders

### ISSUE THREAD

**Issue by juliaelman** [18F/pulse#65]
Had a quick discussion with @konklone this morning about possibly interviewing one of the CIO's we have been in contact with to talk about the dashboard. It would be great to get clarification on information that they would find useful. 

Here are a few suggested questions:

- What agency are you overseeing?
- What are some of the challenges you face when making decisions?
- Is there a particular tool or website that you use for helping make those decisions?
- What kind of information do you find most useful when determining the security protocols used by your web properties?
- Is there a standard that you have in place that the websites you manage are required to take to comply with security standards?

**Comment by gbinal** [comment]
I think those questions are fine but would assume they'd be framed first specific to the topic of HTTPS.  Without that framing, they'd be too broad, right?

**Comment by juliaelman** [comment]
@gbinal I think it would be good to mix in some broad questions and then some more specific. Are there a particular ones that you would like to see changed? Any suggestions on questions to add?

**Comment by juliaelman** [comment]
Unassigned myself, as this is turning into more of a group effort.

**Comment by gbinal** [comment]
What do folks think of closing this?  I'm fine with the user interviews we've now done.  

Yes, we can do more in future sprints, but I feel good about where we've gotten to in this phase 1 of the project.

**Comment by juliaelman** [comment]
@gbinal +1 on closing.
