### ISSUE TITLE
Collect Feedback for Customer Satisfaction Mockups

### ISSUE THREAD

**Issue by gbinal** [18F/pulse#656]
As part of #629, we've put together a set of mockups for a potential customer satisfaction section to pulse.  @smarina04, can you use this issue to assemble the changes you'd like for the next version (v0.3)?  

Here are mockups of a customer satisfaction section, updated with the above data.  

# v0.4

## Domains Tab

![pulse-cst-homepage-1x2](https://cloud.githubusercontent.com/assets/633088/23274687/ab92234a-f9d1-11e6-9c02-2e419a600c3e.png)

## Domains Tab, Showing an Expanded Result

![pulse-cst-homepage-2x2](https://cloud.githubusercontent.com/assets/633088/23274698/b16a49b4-f9d1-11e6-9a77-899afa9ac197.png)

## Domains tab, filtered by an individual service

![pulse-cst-homepage-3x2](https://cloud.githubusercontent.com/assets/633088/23274708/b7549bcc-f9d1-11e6-8ff5-d8805ae24266.png)

## Agencies tab

![pulse-cst-homepage-4x2 copy](https://cloud.githubusercontent.com/assets/633088/23274724/c15f6e3a-f9d1-11e6-9f31-26b9ab9b7273.png)

**Comment by gbinal** [comment]
From @smarina04: 

> Change "Participate in the Digital Analytics Program" title in the mockup to "Use Web-based Customer Satisfaction Surveys"

**Comment by smarina04** [comment]
Maybe we can squeeze in "online" - otherwise we may get pushback because we are only looking for online/web-based surveys vs. any customer surveys.

**Comment by gbinal** [comment]
The above are now updated to say: "Use Online Satisfaction Surveys".

**Comment by gbinal** [comment]
Done.
