### ISSUE TITLE
Integrate a new sites.csv file from analytics.usa.gov

### ISSUE THREAD

**Issue by gbinal** [18F/pulse#664]
The analytics.usa.gov project wanted to add a slightly higher threshold for the [generation](https://github.com/18F/analytics-reporter/blob/master/reports/usa.json#L352-L370) of it's [sites.csv report](https://analytics.usa.gov/data/live/sites.csv) (which provides a list of participating sites).  This was achieved with https://github.com/18F/analytics.usa.gov/issues/449.  

We didn't realize at the time though that pulse [uses that file](https://github.com/18F/pulse/blob/master/meta.yml#L19) as a means of discovering more subdomains for the https scans and that it would prefer the threshold to stay low.  

To resolve this, we're going to generate a new report that uses the lower threshold and update the url that pulse looks to to point to this new file instead.

**Comment by gbinal** [comment]
I've created https://github.com/18F/analytics-reporter/pull/203 to create a new report called `sites_extended` that'll live [here](https://analytics.usa.gov/data/live/sites_extended.csv).  

When it's merged and pushed to production, we should review, merge, and push to production  https://github.com/18F/pulse/pull/665

**Comment by konklone** [comment]
This is integrated.
