### ISSUE TITLE
Json file for Pulse Accessiblity does not contain agencies/domains with 0 accessibility findings

### ISSUE THREAD

**Issue by smarina04** [18F/pulse#681]
The json file they get from Pulse Accessibility does not contain any agencies or domains with 0 errors, which makes external trend analysis incomplete. The Pulse site displays them, but json  doesn't. Can this be fixed?

**Comment by gbinal** [comment]
To confirm, I believe what they are asking for is for the [a11y.json file](https://github.com/18F/pulse/blob/master/static/data/tables/accessibility/a11y.json) (direct link [here](https://staging.pulse.cio.gov/static/data/tables/accessibility/a11y.json)) to include a reference to every domain, even if it has no errors.  

This shouldn't be too hard to do given our recent work to streamline the scanning process.

**Comment by smarina04** [comment]
Ok, thanks. Can this be the top priority? I'd like to have it be fixed asap so that contractors can do trend analysis with the latest scan. Thanks.

**Comment by konklone** [comment]
Fixed in #685.
