### ISSUE TITLE
Create a one-time DAP report at the subdomain level

### ISSUE THREAD

**Issue by gbinal** [18F/pulse#682]

**Comment by konklone** [comment]
Note that excluding redirects will be more important here - and you may want to also exclude sites which return a non-200 status code altogether.

**Comment by gbinal** [comment]
Steps:  
1) Download the [2016 end of term export](https://github.com/GSA/https/blob/master/compliance/data/eot-seeds/eot-2016-seeds.csv), [12-31-16 censys export](https://github.com/GSA/https/blob/master/compliance/data/censys-2016-12-31.csv), [1-1-17 Digital Analytics Program export](https://github.com/GSA/https/blob/master/compliance/data/analytics-domains/all-domains-30-days-2017-01-01.csv), and [12-31-16 HTTPS report export](https://github.com/GSA/https/blob/master/compliance/data/parents-2016-12-31.csv).  
2) Combine them all.  
3) Dedup the list.  
4) Run [domain-scan](https://github.com/18f/domain-scan).  
5) Remove redirects and inactive urls.

**Comment by gbinal** [comment]
Done - https://github.com/18F/g-analytics/tree/18f-pages/projects/dap-subdomain-report
