### ISSUE TITLE
any reason federalregister.gov is not included in DAP section?

### ISSUE THREAD

**Issue by tdlowden** [18F/pulse#698]
federalregister.gov is a live, public-facing, non redirecting site.

Thanks.

**Comment by konklone** [comment]
According to the .gov domain list, federalregister.gov is a property of the Government Publishing Office, a legislative branch agency.

(Note that yes, the [Office of the Federal Register](https://www.ofr.gov) is an office of the National Archives, an executive branch agency. But they do a lot of cross-branch/agency sharing of information, and you can even see that the certificate for https://www.ofr.gov says "Government Publishing Office" next to the URL bar. Government is weird.)

**Comment by tdlowden** [comment]
thanks for the explanation @konklone! Will close.
