### ISSUE TITLE
Searching for agency can give too many domains

### ISSUE THREAD

**Issue by siccovansas** [18F/pulse#714]
When you click on the linked number in 'No. of domains' column on the [By Agency page](https://pulse.cio.gov/https/agencies/), you will get a page showing the search results for the name of the agency. This can result in too many domains though, which is confusing to the user.

E.g., at the By Agency page you see that U. S. Postal Service has 6 domains. When you click on the '6' you're shown a [page listing 7 domains](https://pulse.cio.gov/https/domains/#q=U.%20S.%20Postal%20Service). This is due to `uspsoig.gov` having `U.S. Postal Service, Office of Inspector General` as agency and this matches the search for `U. S. Postal Service`.

This problem occurs in two instances as well on the Dutch Pulse when on the [By Agency page](https://pulse.openstate.eu/https/agencies/) you click on the [Gemeenten agency](https://pulse.openstate.eu/https/domains/#q=Gemeenten) (386 domains shown instead of actual 381 domains) and the [Ministerie van Algemene Zaken agency](https://pulse.openstate.eu/https/domains/#q=Ministerie%20van%20Algemene%20Zaken) (22 domains shown instead of the actual 20 domain, this time actually due to two domains containing the word 'algemene' besides having the word 'Ministerie', 'van' and 'Zaken' being matched because these two domains have 'Ministerie van Binnenlandsze Zaken' as agency).

This isn't a huge problem, but I already had a few confused users running into this.

**Comment by gbinal** [comment]
Thanks, @siccovansas.   You're absolutely right.  Though not a significant issue, it is endemic and would be nice to address.  

For now, the project is in a lull in further development so I don't have a timeframe of when or if we'll get to this issue.  I'm adding to [the backlog](https://github.com/18F/pulse/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Abacklog) for ease of access in the future.  

Thanks.
