### ISSUE TITLE
Data availability and download information

### ISSUE THREAD

**Issue by konklone** [18F/pulse#72]
Could be its own page, or its own section, but we should have a place for "Here's the data!" with the JSON and CSV that we have.

**Comment by jden** [comment]
Should this be published on data.gov? May be getting into uncharted territory here, but are there best practices around agile open data releases where the underlying schema and extent of the data is evolving?

**Comment by jden** [comment]
cross reference #163

**Comment by gbinal** [comment]
Yep, definitely.  We're hoping to address that through #163 soon.

**Comment by konklone** [comment]
For a bunch of reasons, we cut a bunch of open data corners as we were launching the site. Very much hoping to get our house in order on that front in the coming days. Thanks for the nudge, @jden!

**Comment by gbinal** [comment]
@konklone - Let's go with what we have in hand right now, for now. Whether CSVs or JSON and even if numbers as opposed to the processed information on the site, it'll be better to add what we have to /about now and iterate as we go.
