### ISSUE TITLE
Best-Practices

### ISSUE THREAD

**Issue by jalbertbowden** [18F/pulse#733]
Section 508 compliance is a best practice that has been around longer than mandatory HTTPS conversion and digital analytics. That should not only be tracked, but prominently displayed on pulse as well. Document validation should but held to this standard as well, but I'm sure I just lost 99.99999% of anyone who read this with that statement. Happy to convince you all at another time, just ask!

Is there a defined set of best-practices for federal sites?
I can think of a number of the top of my head that I'd like to see in place:
document naming conventions
uri naming conventions
naming conventions
redirects
linkrot
subdomains
foss alternatives offered to citizens
email naming conventions
document creation conventions
cross-browser implementations
cross-platform implementations
cross-device implementations
archiving

Perhaps this isn't the best place for this discussion? If so, I apologize. More than happy to take this to the correct forum.

**Comment by gbinal** [comment]
Hi @jalbertbowden - these are all great ideas.  

There's an accessibility section that is released for agencies as a pilot section of the website and we hope to one day activate it on the public site.  

There's [a page](https://github.com/18F/pulse/blob/master/docs/other-sections.md) where we've been tracking ideas for other sections to the site and I've added a link to this issue to include these ideas in future consideration.  

For now though, we are not actively developing new sections of the site, so I'm going to go ahead and close the issue.  Thanks for the feedback though.  We'll be sure to post issues to this repo if and when the project is able to expand further.
