### ISSUE TITLE
Broken link in FAQ 

### ISSUE THREAD

**Issue by sidewalkballet** [18F/pulse#771]
:wave: I came across a broken link in the FAQ - 

On this page: https://pulse.cio.gov/about/#what-domains-are-being-measured
This text: `official .gov domain list`
Leads to here, which 404s: https://github.com/GSA/data/tree/gh-pages/dotgov-domains

**Comment by konklone** [comment]
Good catch, thank you. We'd updated the branch in that repo to be `master` instead of `gh-pages`, and I thought I'd caught all the instances of it, but had missed this one!
