### ISSUE TITLE
DAP stats page front end implementation

### ISSUE THREAD

**Issue by juliaelman** [18F/pulse#78]
Below are two PNG layouts for the Pulse DAP pages. A few tasks that need to be completed are:

- [x] Dynamically retrieving the DAP compliance stats into the page and placing into a dataTable
- [x] Copy at the top that explains how we came to this aggregate data and what DAP is
- [x]  Grouping the current data set by agency

![dap - filtered by domain](https://cloud.githubusercontent.com/assets/955558/7573598/dae0e3c4-f7f4-11e4-96dc-840f4ba59e55.png)

![dap - filtered by agency](https://cloud.githubusercontent.com/assets/955558/7573600/dc59c1da-f7f4-11e4-82cb-c05f30b70d8e.png)

**Comment by juliaelman** [comment]
Making not of a comment made by @konklone from round 3 wireframes feedback:

"I personally think the definition and methodology behind the terms we grade agencies on will be necessary for MVP (though not necessary for Sprint 2 / these wireframes) in order for the site to be fair and helpful."

**Comment by konklone** [comment]
Closed by #110.
