### ISSUE TITLE
(Likely) Incorrect Development Status classifier in setup.py

### ISSUE THREAD

**Issue by buckley-w-david** [18F/pulse#785]
For CDSs fork, we're pre-alpha at this stage, so the Development Status classifier that I put in the `setup.py` file reflects that:
```
. . .
    classifiers=[
        'Development Status :: 2 - Pre-Alpha',
        'Intended Audience :: Developers',
        'Natural Language :: English',
        'Programming Language :: Python :: 3',
    ],
. . .
```
However when the changes to make `data` into a package were merged upstream into this repo, I did not even consider that this is likely not true for 18F.

I'm not sure what classification is right for this repo, but I figured it's likely not what's there now.

**Comment by konklone** [comment]
I can't bring myself to care. ;) And I don't know the right classifier value off the top of my head. Feel free to update it in a future PR at your leisure.

**Comment by gbinal** [comment]
The pulse.cio.gov website has been decommissioned and set to redirect to digitaldashboard.gov.  Closing this issue.
