### ISSUE TITLE
Responsive fixes for various different layouts

### ISSUE THREAD

**Issue by juliaelman** [18F/pulse#95]
- [x] Determine screen widths for break points
- [x] Implement break points in stylesheets
- [x] Create fixes in various pages
- [ ] Test on various devices

**Comment by konklone** [comment]
For the table itself, I think we're going to want to use the `Responsive` extension:

https://www.datatables.net/extensions/responsive

I've looked through its docs, and I think it'll be acceptable. Prioritizing other stuff until post-27th, but happy to field that part of this ticket after that.

**Comment by juliaelman** [comment]
Current breakpoints are: 480px, 767px, 1024px and 1200px.
