### ISSUE TITLE
remove unneeded word 

### ISSUE THREAD

**Issue by gbinal** [18F/pulse#99]
On `https://pulse.18f.gov/https/` and `https://pulse.18f.gov/analytics/`, the toggle that changes how many entries are on a page doesn't really need the word `entries` and would look a bit better without it.  

In other words, I'm suggesting this:  

![screen shot 2015-05-18 at 2 24 35 pm](https://cloud.githubusercontent.com/assets/633088/7687264/031d9fa6-fd6a-11e4-8505-3e77e9e6167f.png)

become this:  

 
![screen shot 2015-05-18 at 2 26 22 pm](https://cloud.githubusercontent.com/assets/633088/7687263/0033090c-fd6a-11e4-9404-ccfa29a7ede6.png)

**Comment by konklone** [comment]
The awkward styling here was fixed in a previous PR.

![screenshot from 2015-05-25 16 12 57](https://cloud.githubusercontent.com/assets/4592/7801847/f1b2e4f8-02f8-11e5-8c44-e98fe78cd1fa.png)
